import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import OpenAI from "openai";
import { ITask } from "../models/task.model";
import { IProject } from "../models/project.model";
import { parseGithubUrl, getFileContent } from "./github";

const deepseek = new OpenAI({
  apiKey: process.env.DEEPSEEK_API_KEY!,
  baseURL: "https://api.deepseek.com",
});

// ─── Prompt ───────────────────────────────────────────────────────────────────

const EXECUTOR_SYSTEM = `You are a senior software engineer implementing one specific file change based on a plan.

You will be given:
1. A task title and description
2. An implementation plan (markdown)
3. ONE source file to modify

Your job is to produce the COMPLETE updated content for that single file.

RULES:
- Respond with ONLY the raw file content — no markdown fences, no explanation, no other text.
- Output the COMPLETE new file content, not a diff or snippet.
- Preserve all existing logic, imports, and code that is NOT related to this task.
- Follow the exact same code style, patterns, and conventions as the existing file.`;

function buildSingleFilePrompt(
  task: ITask,
  file: { path: string; content: string }
): string {
  return `Task: ${(task as any).title}
Description: ${(task as any).description || "(no description)"}

Implementation Plan:
${task.planMarkdown}

File to modify: ${file.path}
--- CURRENT CONTENT ---
${file.content}
--- END ---

Return the complete updated content of ${file.path} only. No fences, no explanation.`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// Extracts file paths from the planMarkdown generated by Stage 1.
// Prioritises the "Files to change" markdown table rows to avoid collecting
// the short relative paths that appear in step-by-step prose section headers.
function extractPathsFromPlan(plan: string): string[] {
  const tablePaths: string[] = [];

  // Extract from table rows first: | `path` | or | path |
  for (const m of plan.matchAll(/\|\s*`?([^\s|`]+\.[a-zA-Z]{1,10})`?\s*\|/g)) {
    const p = m[1].trim();
    if (p.includes("/")) tablePaths.push(p);
  }

  if (tablePaths.length > 0) {
    // Deduplicate: drop any path that is a short suffix of a longer path already collected
    const unique: string[] = [];
    for (const p of tablePaths) {
      const covered = unique.some((u) => u === p || u.endsWith("/" + p));
      if (!covered) unique.push(p);
    }
    return unique;
  }

  // Fallback: collect all backtick-wrapped paths anywhere in the document
  const fallback = new Set<string>();
  for (const m of plan.matchAll(/`([^`]+\.[a-zA-Z]{1,10})`/g)) {
    const p = m[1].trim();
    if (p.includes("/") && !p.includes(" ")) fallback.add(p);
  }
  return Array.from(fallback);
}

function exec(cmd: string, cwd: string, env?: NodeJS.ProcessEnv): string {
  return execSync(cmd, { cwd, stdio: "pipe", env: env ?? process.env }).toString().trim();
}

function buildAuthenticatedCloneUrl(
  owner: string,
  repo: string,
  token: string
): string {
  // Strip accidental URL prefixes if someone pastes a full URL instead of a PAT
  const cleanToken = token.replace(/^https?:\/\/[^@]*@?/i, "").replace(/['"]/g, "").trim();
  return `https://${cleanToken}@github.com/${owner}/${repo}.git`;
}

async function openPullRequest(
  owner: string,
  repo: string,
  branch: string,
  baseBranch: string,
  title: string,
  body: string,
  token: string
): Promise<string> {
  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls`,
    {
      method: "POST",
      headers: {
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ title, head: branch, base: baseBranch, body }),
    }
  );

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(
      `GitHub PR creation failed (${response.status}): ${(err as any).message ?? JSON.stringify(err)}`
    );
  }

  const pr = await response.json();
  return (pr as any).html_url as string;
}

async function getDefaultBranch(
  owner: string,
  repo: string,
  token: string
): Promise<string> {
  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}`,
    {
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${token}`,
      },
    }
  );
  if (!response.ok) return "main";
  const data = await response.json();
  return (data as any).default_branch ?? "main";
}

// ─── Core executor ────────────────────────────────────────────────────────────

export async function runPlanAgent(
  task: ITask,
  project: IProject,
  token: string,
  baseBranchOverride?: string
): Promise<{ prUrl: string; log: string }> {

  const parsed = parseGithubUrl(project.repoUrl!);
  if (!parsed) throw new Error("Invalid GitHub repo URL on project.");
  const { owner, repo } = parsed;

  const tmpDir = path.join(
    process.platform === "win32" ? "C:\\Temp" : "/tmp",
    `agent-${task._id}`
  );

  try {
    // 1. Clone
    if (fs.existsSync(tmpDir)) {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
    const cloneUrl = buildAuthenticatedCloneUrl(owner, repo, token);
    execSync(`git clone "${cloneUrl}" "${tmpDir}"`, { stdio: "pipe" });

    // Strip credentials from remote so they don't appear in logs
    exec(
      `git remote set-url origin https://github.com/${owner}/${repo}.git`,
      tmpDir
    );

    // Configure git identity for the commit
    exec(`git config user.email "agent@projectflow.app"`, tmpDir);
    exec(`git config user.name "ProjectFlow Agent"`, tmpDir);

    // 2. Extract file paths from planMarkdown — reuses the planner's file selection,
    //    no extra DeepSeek call needed. Scans for paths in the "Files to change" table
    //    and any "FILE: path" markers left by the planner prompt.
    const selectedPaths = extractPathsFromPlan(task.planMarkdown!);
    console.log("[agentExecutor] Files from plan:", selectedPaths);

    // 3. Fetch file contents
    const fileResults = await Promise.all(
      selectedPaths.map((p: string) =>
        getFileContent(owner, repo, p, token).catch(() => null)
      )
    );
    const files = fileResults.filter(
      (f): f is { path: string; content: string } => f !== null
    );

    // 5. Ask DeepSeek to implement each file individually to avoid token limit truncation
    const implementFile = async (file: { path: string; content: string }): Promise<string> => {
      const userPrompt = buildSingleFilePrompt(task, file);
      const response = await deepseek.chat.completions.create({
        model: "deepseek-v4-flash",
        messages: [
          { role: "system", content: EXECUTOR_SYSTEM },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.1,
        max_tokens: 8192,
      });

      const finishReason = response.choices[0]?.finish_reason;
      const raw = response.choices[0]?.message?.content?.trim() ?? "";
      console.log(`[agentExecutor] ${file.path} — finish_reason=${finishReason} length=${raw.length}`);
      if (finishReason === "length") {
        throw new Error(`DeepSeek truncated output for ${file.path} — file may be too large.`);
      }

      // Strip markdown fences if the model wrapped the output anyway
      return raw.replace(/^```[a-zA-Z]*\n?/, "").replace(/\n?```$/, "");
    };

    const changes: { path: string; content: string }[] = [];
    for (const file of files) {
      console.log(`[agentExecutor] implementing ${file.path}...`);
      const content = await implementFile(file);
      changes.push({ path: file.path, content });
    }

    if (changes.length === 0) {
      throw new Error("No files were fetched from the repository — check that the paths in the plan exist.");
    }

    // 6. Write files into the cloned repo
    for (const { path: filePath, content } of changes) {
      const abs = path.join(tmpDir, filePath);
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content, "utf-8");
    }

    // 7. Verify something actually changed
    const diffStat = exec("git diff --stat", tmpDir);
    if (!diffStat) {
      throw new Error(
        "Agent made no changes — the generated file contents matched the originals."
      );
    }

    // 8. Checkout feature branch, commit, push
    const taskTitle = (task as any).title as string;
    const titleSlug = taskTitle
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 40);
    const branchName = `agent/${titleSlug}-${task._id.toString().slice(-6)}`;
    const baseBranch = baseBranchOverride ?? await getDefaultBranch(owner, repo, token);

    exec(`git checkout -b ${branchName}`, tmpDir);
    exec("git add -A", tmpDir);
    exec(
      `git commit -m "feat: ${taskTitle.replace(/"/g, "'")} (AI agent)"`,
      tmpDir
    );

    // Push using GIT_ASKPASS to supply the token — fully bypasses Windows credential manager
    const cleanToken = token.replace(/['"]/g, "").trim();
    const askpassScript = process.platform === "win32"
      ? path.join(tmpDir, "askpass.bat")
      : path.join(tmpDir, "askpass.sh");
    if (process.platform === "win32") {
      fs.writeFileSync(askpassScript, `@echo off\necho ${cleanToken}\n`, "utf-8");
    } else {
      fs.writeFileSync(askpassScript, `#!/bin/sh\necho '${cleanToken}'\n`, "utf-8");
      fs.chmodSync(askpassScript, 0o755);
    }
    exec(`git remote set-url origin "https://${owner}@github.com/${owner}/${repo}.git"`, tmpDir);
    exec(`git push origin "${branchName}"`, tmpDir, {
      ...process.env,
      GIT_ASKPASS: askpassScript,
      GIT_TERMINAL_PROMPT: "0",
    });

    // 9. Open PR
    const changedFiles = changes.map((c) => `- \`${c.path}\``).join("\n");
    const prBody = `## AI-generated implementation\n\n**Task:** ${taskTitle}\n\n**Changed files:**\n${changedFiles}\n\n---\n*Generated by ProjectFlow Agent using DeepSeek. Please review carefully before merging.*`;

    const prUrl = await openPullRequest(
      owner,
      repo,
      branchName,
      baseBranch,
      `feat: ${taskTitle} (AI agent)`,
      prBody,
      token
    );

    const log = `Implemented ${changes.length} file(s): ${changes.map((c) => c.path).join(", ")}. PR opened at ${prUrl}`;
    return { prUrl, log };
  } finally {
    // Always clean up temp dir
    try {
      if (fs.existsSync(tmpDir)) {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    } catch (cleanupErr) {
      console.warn("[agentExecutor] Cleanup failed:", cleanupErr);
    }
  }
}
